# Generated by Django 5.0.2 on 2024-02-21 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='creator_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_creator', to='courses.customuser'),
        ),
        migrations.AlterField(
            model_name='studenthomework',
            name='homework_content',
            field=models.JSONField(),
        ),
    ]
