# Generated by Django 5.0.2 on 2024-02-21 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_creator_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='creator_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='course',
            name='creator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_creator', to='courses.customuser'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(related_name='courses_taught', to='courses.customuser'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('tutor', 'Тьютор'), ('producer', 'Продюсер')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='completion_time',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Подтверждена'), ('rejected', 'Отклонена')], default='pending', max_length=20)),
                ('date_enrolled', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.customuser')),
            ],
            options={
                'verbose_name': 'Запрос на обучение',
                'verbose_name_plural': 'Запросы на обучение',
            },
        ),
    ]
