# Generated by Django 5.0.2 on 2024-02-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_studenthomework_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='studenthomework',
            name='homework_content',
            field=models.FileField(upload_to='homework_files/'),
        ),
    ]
