# Generated by Django 5.0.2 on 2024-03-21 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='course_files/'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='shop_files/'),
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievements_name', models.CharField(max_length=255)),
                ('achievements_description', models.TextField()),
                ('achievements_date', models.DateField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='achievement_pictures/')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Достижение студента',
                'verbose_name_plural': 'Достижения студентов',
            },
        ),
    ]
