# Generated by Django 5.0.2 on 2024-04-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_lesson_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
