# Generated by Django 5.0.2 on 2024-04-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_shopitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
