# Generated by Django 5.0.2 on 2024-05-11 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_shopitem_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.IntegerField(default=0)),
                ('shoes', models.IntegerField(default=0)),
                ('bruke', models.IntegerField(default=0)),
                ('tshort', models.IntegerField(default=0)),
                ('arm', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонаж',
            },
        ),
    ]
