# Generated by Django 5.0.2 on 2024-05-22 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_filemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filemodel',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AddField(
            model_name='filemodel',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.lesson'),
            preserve_default=False,
        ),
    ]
