# Generated by Django 5.0.2 on 2024-05-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_filemodel_options_filemodel_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='id_element',
            field=models.IntegerField(default=0),
        ),
    ]
