# Generated by Django 5.0.2 on 2024-05-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_filemodel_id_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthomework',
            name='homework_content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
